const productos = [
    {id: 1, categoryId: 'Shōnen', name: 'One Piece', description:'One Piece narra la historia de un joven llamado Monkey D. Luffy, que inspirado por su amigo pirata Shanks, comienza un viaje para alcanzar su sueño, ser el Rey de los piratas, para lo cual deberá encontrar el tesoro One Piece dejado por el anterior rey de los piratas Gol D. Roger.',  price: 1200, stock: 10, img: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/2239c7b46b2e491ae33b33ff980e9fb1.jpe'},
    {id: 2, categoryId: 'Seinen', name: 'Code Geass', description: 'Code Geass se desarrolla en una realidad alternativa donde el Sacro Imperio de Britannia, una superpotencia internacional, ha conquistado más de un tercio del planeta. El mundo, principalmente, es dividido entre esta y otras dos superpotencias: la Federación China y la Unión Europea.', price: 1500, stock: 5, img: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/efb29ad752e647212b3e199da7748e9e.jpe'},
    {id: 3, categoryId: 'Kodomo', name: 'Pokemon', description: 'La serie sigue las aventuras de un impetuoso y joven entrenador llamado Ash Ketchum, y de Pikachu, su compañero Pokémon, mientras viajan por el mundo Pokémon visitando destinos exóticos, conociendo a montones de personas y Pokémon nuevos e interesantes, y viviendo muchas y emocionantes aventuras', price: 2000, stock: 2, img: 'https://lzd-img-global.slatic.net/g/p/51ab4db427f4f43035ee4d6ac95978ad.jpg_720x720q80.jpg_.webp'},
    {id: 5, categoryId: 'Shōjo', name: 'Toradora!', description: 'La historia es simple a más no poder, es un Slice of Life que narra la vida del estudiante Ryuuji Takasu, un chico que tiene una apariencia amenazadora pero que en realidad es muy amable, trabajador y obsesionado con el orden y la limpieza, mientras empieza un nuevo año escolar.', price: 800, stock: 20, img: 'https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/6503d5063921785f0d94b33d26b5e4cc.jpe'},
    {id: 6, categoryId: 'Shōnen', name: 'Naruto', description: 'La obra narra la historia de un ninja huérfano adolescente llamado Naruto Uzumaki, cuyos padres murieron en el ataque del Zorro Demonio de Nueve Colas, y quien aspira a convertirse en Hokage (líder de su aldea) con el propósito de ser reconocido como alguien importante dentro de la aldea y entre sus compañeros.',price: 1300, stock: 12, img: 'https://i.pinimg.com/564x/96/59/e3/9659e30be69e55f9f3cfc442d4d5bba3.jpg'},
    {id: 7, categoryId: 'Seinen', name: 'Vinland Saga',description: 'es una serie de manga escrita e ilustrada por Makoto Yukimura. La historia está ambientada en la región de Danelaw en el siglo XI y se basa en varias sagas islandesas: el Flateyjarbók, la Saga de los groenlandeses y la Saga de Erik el Rojo.', price: 1200, stock: 8, img: 'https://d3ugyf2ht6aenh.cloudfront.net/stores/001/318/183/products/20thcenturyboys05-1991-3c9fb2215cb22955c516673344732383-480-0.webp'},
    {id: 8, categoryId: 'Kodomo', name: 'Bakugan', description: 'es una serie de anime bajo la dirección de Mitsuo Hashimoto basada en Bakugan, un juego de cartas estratégico creado por Sega Toys y Spin Master usando naipes metálicos y figuras móviles en miniatura. La historia se centra en las vidas de unas criaturas llamadas Bakugan y los peleadores que las dominan.',price: 800, stock: 30, img: 'https://i.pinimg.com/564x/3d/93/de/3d93de90c7d5093195610f7042935908.jpg'},
    {id: 9, categoryId: 'Shōjo', name: 'Banana Fish', description: 'Banana Fish es una serie anime que sigue la historia de Ash Lynx, un chico bastante atractivo y un gran luchador que forma una pandilla a sus 17 años en plena ciudad de Nueva York. Pero una noche, un hombre tiroteado por sus secuaces le da a Ash una dirección con dos palabras: Banana Fish.',price: 1000, stock: 40, img: 'https://d3ugyf2ht6aenh.cloudfront.net/stores/001/318/183/products/whatsapp_image_2020-10-02_at_11-21-4715608b1baf82e3bd16726922687470-480-0.webp'},
]

export let mockFetch = (time) => {
    return new Promise ((resolve, reject) => {
        setTimeout(() => {
            resolve(productos)
        }, time)
    })
}